### ISSUE TITLE
.lproj not found in xcodeproj issue

### ISSUE THREAD

**Issue by i-miss-old-mmorpg** [yasirkula/UnityMobileLocalizedAppTitle#1]
Hi.

After exported from Windows to Xcode, the path setting of .lproj are still the same as Windows'. It will become like "/Users/username/Desktop/UnityProject123/C:/Users/username/Desktop/UnityProject123", causing error of not found.

For now I need to manually change all .lproj paths inside xcodeproj every time. Is there any better solution?

**Comment by yasirkula** [comment]
Thank you for reporting this issue. Firstly, I'd like to mention that I didn't encounter this problem in our own iOS builds (built on Mac devices, though).

The error must be related to this line: https://github.com/yasirkula/UnityMobileLocalizedAppTitle/blob/ce28336b837303aa2fd9d03557898d89290ea5db/Plugins/LocalizedAppTitle/Editor/LocalizedAppTitlePostProcessBuild.cs#L503

All example codes of AddFolderReference that I could find online use the same syntax: first parameter is absolute path, second is relative path, third is PBXSourceTree.Source. Either something on Unity-side must've changed by mistake in latest Unity versions, or the value of _localizationFolder_ is somehow not correct. I'd recommend printing its value to the console to see what it outputs.

**Comment by FunRobDev** [comment]
Hi there!

I am using Unity 2022.3.10f and having the same issue.

A working solution is around line 500, replace
`string localizationFolderGuid = pbxProject.AddFolderReference( localizationFolder, Path.GetFileName( localizationFolder ), PBXSourceTree.Source );`
with this:
```
#if UNITY_2022_3_OR_NEWER
   string localizationFolderGuid = pbxProject.AddFolderReference( "", Path.GetFileName(localizationFolder), PBXSourceTree.Source);
#else
   string localizationFolderGuid = pbxProject.AddFolderReference( localizationFolder, Path.GetFileName( localizationFolder ), PBXSourceTree.Source );
#endif
```

yasirkula, I don't know when did Unity introduce this change, but you can insert my fix in the source code with this UNITY_2022_3_OR_NEWER constant, and maybe lower it the value later if somebody faces the same issue.

God Bless till then
FunRobDev

**Comment by yasirkula** [comment]
I shall give it a shot when I get the chance.

**Comment by yasirkula** [comment]
@FunRobDev I'd like to do it the proper way if possible. I've modified the post processor script so that it won't output Windows paths and hopefully resolve this issue. I couldn't test it yet because I don't have access to a Mac workstation. If you get the chance, could you give it a shot?

[LocalizedAppTitlePostProcessBuild.zip](https://github.com/yasirkula/UnityMobileLocalizedAppTitle/files/12775607/LocalizedAppTitlePostProcessBuild.zip)

**Comment by FunRobDev** [comment]
Hi @yasirkula, yes, I will gladly test it for you, but I will need a week or so. (I have fever, lying in bed). I will ping you. Cheers!

**Comment by yasirkula** [comment]
Get well soon and thank you ^^ If I can test it on a friend's computer in the meantime, I'll let you know.

**Comment by yasirkula** [comment]
We've created a project on Mac and it worked. Now waiting for your Windows build results before releasing the fix.

**Comment by FunRobDev** [comment]
Hi @yasirkula,
I tested now the attached LocalizedAppTitlePostProcessBuild.zip 
Everything works fine now! 
You fix seems super!

I tested with language codes: en, hu. 
I used Windows 10 with Unity 2022.3.10f, and macOS12.1 with Xcode13.2

**Comment by yasirkula** [comment]
Thank you!
